# Generated by Django 5.2.9 on 2026-01-14 16:48

import datetime
import django.core.validators
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('meal_type', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack'), ('O', 'Other')], max_length=1)),
                ('protein_per_100g', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('carbohydrates_per_100g', models.DecimalField(blank=True, decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('fat_per_100g', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('kcal_per_100g', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('food_item_mass_in_grams', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_consumed', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('protein_per_100g'), '*', models.F('food_item_mass_in_grams')), '/', models.Value(100)), output_field=models.FloatField())),
                ('carbohydrates_consumed', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('carbohydrates_per_100g'), '*', models.F('food_item_mass_in_grams')), '/', models.Value(100)), output_field=models.FloatField())),
                ('fat_consumed', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('fat_per_100g'), '*', models.F('food_item_mass_in_grams')), '/', models.Value(100)), output_field=models.FloatField())),
                ('kcal_consumed', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('kcal_per_100g'), '*', models.F('food_item_mass_in_grams')), '/', models.Value(100)), output_field=models.FloatField())),
            ],
        ),
    ]
