# Generated by Django 5.2.9 on 2026-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietstats',
            name='kcal_per_100g',
            field=models.FloatField(),
        ),
    ]
