# Generated by Django 5.2.9 on 2026-01-14 17:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0002_alter_dietstats_kcal_per_100g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietstats',
            name='kcal_per_100g',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
    ]
