# Generated by Django 5.2.9 on 2026-01-26 17:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restApi", "0002_fooddescription_foodentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FoodEntry",
            new_name="FoodEntryModel",
        ),
        migrations.CreateModel(
            name="FoodDescriptionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("prtn100", models.FloatField()),
                ("carb100", models.FloatField()),
                ("fat100", models.FloatField()),
                ("kcal100", models.FloatField()),
                ("created_at", models.DateTimeField(default=datetime.datetime.today)),
                ("first_created_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated_date", models.DateTimeField(auto_now=True)),
                (
                    "description_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_descriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="foodentrymodel",
            name="description",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="restApi.fooddescriptionmodel",
            ),
        ),
        migrations.DeleteModel(
            name="FoodDescription",
        ),
    ]
