# Generated by Django 5.2.9 on 2026-01-14 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0003_alter_dietstats_kcal_per_100g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietstats',
            name='carbohydrates_per_100g',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dietstats',
            name='fat_per_100g',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='dietstats',
            name='protein_per_100g',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
