# Generated by Django 5.2.9 on 2026-02-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "restApi",
            "0003_rename_foodentry_foodentrymodel_fooddescriptionmodel_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodentrymodel",
            name="first_created_date",
        ),
        migrations.RemoveField(
            model_name="foodentrymodel",
            name="last_updated_date",
        ),
    ]
