# Generated by Django 5.2.9 on 2026-01-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0004_alter_dietstats_carbohydrates_per_100g_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietstats',
            old_name='name',
            new_name='meal_name',
        ),
    ]
