# Generated by Django 5.2.9 on 2026-01-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0005_rename_name_dietstats_meal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietstats',
            name='carbohydrates_per_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dietstats',
            name='fat_per_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dietstats',
            name='food_item_mass_in_grams',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dietstats',
            name='kcal_per_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dietstats',
            name='protein_per_100g',
            field=models.FloatField(),
        ),
    ]
