# Generated by Django 5.2.9 on 2026-01-24 16:23

import datetime
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('meal_type', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack'), ('O', 'Other')], max_length=1)),
                ('protein_per_100g', models.FloatField()),
                ('sugar_per_100g', models.FloatField()),
                ('fat_per_100g', models.FloatField()),
                ('kcal_per_100g', models.FloatField()),
                ('food_item_mass_in_grams', models.FloatField()),
                ('protein_consumed', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('protein_per_100g'), '*', models.F('food_item_mass_in_grams')), '/', models.Value(100)), output_field=models.FloatField())),
                ('sugar_consumed', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('sugar_per_100g'), '*', models.F('food_item_mass_in_grams')), '/', models.Value(100)), output_field=models.FloatField())),
                ('fat_consumed', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('fat_per_100g'), '*', models.F('food_item_mass_in_grams')), '/', models.Value(100)), output_field=models.FloatField())),
                ('kcal_consumed', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('kcal_per_100g'), '*', models.F('food_item_mass_in_grams')), '/', models.Value(100)), output_field=models.FloatField())),
            ],
        ),
    ]
